window.Garden.elements = {
  desktop: document.querySelector('#desktop'),
  themeToggle: document.querySelector('#themeToggle'),
  greeting: document.querySelector('#greeting'),
  time: document.querySelector('#time'),
  clockModeLabel: document.querySelector('#clockModeLabel'),
  clockModeButtons: document.querySelectorAll('[data-clock-mode]'),
  timerSetup: document.querySelector('#timerSetup'),
  timerMinutes: document.querySelector('#timerMinutes'),
  timerStart: document.querySelector('#timerStart'),
  timerPause: document.querySelector('#timerPause'),
  timerReset: document.querySelector('#timerReset'),
  date: document.querySelector('#date'),
  calendarGrid: document.querySelector('#calendarGrid'),
  yearPercent: document.querySelector('#yearPercent'),
  yearBar: document.querySelector('#yearBar'),
  quoteCard: document.querySelector('#quoteCard'),
  quoteText: document.querySelector('#quoteText'),
  quoteSource: document.querySelector('#quoteSource'),
  bookmarkGrid: document.querySelector('#bookmarkGrid'),
  projectGrid: document.querySelector('#projectGrid'),
  projectsProfile: document.querySelector('#projectsProfile'),
  navLinks: document.querySelectorAll('.side-nav a'),
  notesToggle: document.querySelector('#notesToggle'),
  noteWall: document.querySelector('#noteWall'),
  resetLayout: document.querySelector('#resetLayout'),
  musicAudio: document.querySelector('#musicAudio'),
  musicToggle: document.querySelector('#musicToggle'),
  musicProgress: document.querySelector('#musicProgress'),
  songTitle: document.querySelector('#songTitle'),
  songArtist: document.querySelector('#songArtist'),
  refreshWeather: document.querySelector('#refreshWeather'),
  weatherIcon: document.querySelector('#weatherIcon'),
  weatherTemp: document.querySelector('#weatherTemp'),
  weatherText: document.querySelector('#weatherText'),
  weatherPlace: document.querySelector('#weatherPlace'),
  favoriteForm: document.querySelector('#favoriteForm'),
  favoriteGrid: document.querySelector('#favoriteGrid'),
  favoriteTitle: document.querySelector('#favoriteTitle'),
  favoriteUrl: document.querySelector('#favoriteUrl'),
  favoriteDescription: document.querySelector('#favoriteDescription'),
  favoriteTip: document.querySelector('#favoriteTip'),
  selectAllFavorites: document.querySelector('#selectAllFavorites'),
  deleteSelectedFavorites: document.querySelector('#deleteSelectedFavorites')
};




